avatar_url
: 
"https://avatars.githubusercontent.com/u/57013854?v=4"
events_url
: 
"https://api.github.com/users/azemazer/events{/privacy}"
followers_url
: 
"https://api.github.com/users/azemazer/followers"
following_url
: 
"https://api.github.com/users/azemazer/following{/other_user}"
gists_url
: 
"https://api.github.com/users/azemazer/gists{/gist_id}"
gravatar_id
: 
""
html_url
: 
"https://github.com/azemazer"
id
: 
57013854
login
: 
"azemazer"
node_id
: 
"MDQ6VXNlcjU3MDEzODU0"
organizations_url
: 
"https://api.github.com/users/azemazer/orgs"
received_events_url
: 
"https://api.github.com/users/azemazer/received_events"
repos_url
: 
"https://api.github.com/users/azemazer/repos"
score
: 
1
site_admin
: 
false
starred_url
: 
"https://api.github.com/users/azemazer/starred{/owner}{/repo}"
subscriptions_url
: 
"https://api.github.com/users/azemazer/subscriptions"
type
: 
"User"
url
: 
"https://api.github.com/users/azemazer"